TipOfTheDay.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TipOfTheDay.Domain.Abstract;
using TipOfTheDay.Domain.Concrete;
using TipOfTheDay.Domain.Entities;

namespace TipOfTheDay.Controllers
{
    public class AdminController : Controller
    {
        private ITipRepository tipRepo;

        // Used by the MVC framework
        public AdminController()
        {
            tipRepo = new TipRepository();
        }

        // Just for testing
        public AdminController(ITipRepository repo)
        {
            tipRepo = repo;
        } 
        
        // GET: /Admin/
        public ActionResult Index()
        {
            return View(tipRepo.GetTips());
        }

        public ViewResult Edit(int id)
        {
            Tip tip = tipRepo.GetTips().FirstOrDefault(t => t.TipId == id);
            return View(tip);
        }

        [HttpPost]
        public ActionResult Edit(Tip tip, List<Tag> tags)
        {
           foreach(Tag tag in tags)    // tags were not persisted as part of tip, need to add them back
              tip.Tags.Add(tag);      // Warning: These tags just have Id's - the rest of the properties will be restored in the repository
            tipRepo.UpdateTip(tip);
            return RedirectToAction("Index");
        }

        public ViewResult AddTip()
        {
            Tip tip = new Tip();
            tip.Author = (Member)Session["User"];
            return View("Edit", new Tip());
        }

        [HttpPost]
        public ActionResult AddTip(Tip tip, List<Tag> tags)
        {
            // TODO process tags
            tip.Author = (Member)Session["User"];
            tipRepo.SaveTip(tip);
            return RedirectToAction("Index");
        }


        public ActionResult Init()
        {
            tipRepo.Init();
            return RedirectToAction("Index");
        }
    }
}

TipOfTheDay.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TipOfTheDay.Domain.Abstract;
using TipOfTheDay.Domain.Concrete;
using TipOfTheDay.Domain.Entities;

// Written by Brian Bird, 2/16/2012
// MVC web site example

namespace TipOfTheDay.WebUI.Controllers
{
    public class HomeController : Controller
    {
        ITipRepository tipRepo;

        // The default constructor is called by the framework
        public HomeController()
        {
            // Choose the fake or real repository below: 
            tipRepo = new Domain.Concrete.TipRepository();
        }

        // Use this for dependency injection
        public HomeController(ITipRepository repo)
        {
            tipRepo = repo;
        }

        public int PageSize = 1;    // Number of items per page

        public ViewResult Index()
        {
            if (tipRepo.GetTips().Count() == 0) // Just do this the first time the db is created
                tipRepo.Init();

            Tip todaysTip = tipRepo.GetTip(new DateTime(2012, 3, 1));   // TODO use today's day and month
            return View(todaysTip);
        }

        public ViewResult TipList()
        {
            return View(tipRepo.GetTips());
        }

    }
}

TipOfTheDay.WebUI/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TipOfTheDay.Domain.Abstract;
using TipOfTheDay.Domain.Concrete;
using TipOfTheDay.Domain.Entities;

namespace TipOfTheDay.Controllers
{
    public class MemberController : Controller
    {
        IMemberRepository memberRepo;

        // The default constructor is called by the framework
        public MemberController()
        {
            // Choose the fake or real repository below: 
            memberRepo = new MemberRepository();
        }

        // Use this for dependency injection
        public MemberController(IMemberRepository repo)
        {
            memberRepo = repo;
        }        //
        // GET: /User/
        const string USER = "User";


        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(Member user)
        {
            if (user.Name == null) // This is a log-in
            {
                user = memberRepo.GetMembers().FirstOrDefault(m => m.Email == user.Email);
                if (null == user)
                    RedirectToAction("Index");  //User not found, try again
            }
            else     // This is a registration
            {
                memberRepo.SaveMember(user);
            }

            Session[USER] = user;

            return RedirectToAction("Index", "Home");
        }

    }
}

TipOfTheDay.WebUI/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TipOfTheDay.Domain.Abstract;
using TipOfTheDay.Domain.Concrete;
using TipOfTheDay.Domain.Entities;

namespace TipOfTheDay.Controllers
{
    public class SearchController : Controller
    {

       private ITipRepository tipRepo;
       private IMemberRepository memberRepo;

        // Used by the MVC framework
        public SearchController()
        {
            tipRepo = new TipRepository();
            memberRepo = new MemberRepository();
        }

        // Just for testing
        public SearchController(ITipRepository tRepo, IMemberRepository mRepo)
        {
            tipRepo = tRepo;
            memberRepo = mRepo;
        } 
        
        // GET: /Admin/
        public ActionResult FindTipByAuthor()
        {
            return View(memberRepo.GetMembers());
        }

        [HttpPost]
        public ActionResult FindTipByAuthor(int memberId)
        {
            int num = memberId;
            IEnumerable<Tip> tips = from t in tipRepo.GetTips()
                       where t.Author.MemberId == memberId
                       select t;
            return View("TipList", tips);
        }

    }
}

TipOfTheDay.WebUI/Views/Admin/Edit.cshtml
@model TipOfTheDay.Domain.Entities.Tip

@{
    ViewBag.Title = "Edit Tip: "  + @Model.Title;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit Tip:  @Model.Title</h2>

@using (Html.BeginForm())
{
    @Html.EditorForModel()

    <h3>Tags</h3>
    for (int i = 0; i < Model.Tags.Count(); i++) 
    {
        <fieldset>
            <legend>Tag @(i + 1): @Model.Tags[i].Word</legend>
            @Html.Hidden("[" + i + "].TagId", Model.Tags[i].TagId)
        </fieldset>
    }
    
    <input type="submit" value="Save" />
    @Html.ActionLink("Cancel and return to List", "Index")

}

TipOfTheDay.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<TipOfTheDay.Domain.Entities.Tip>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Tip List</h2>

<p>
    @Html.ActionLink("Create New Tip", "AddTip")
</p>
<table>
    <tr>
        <th>
            Title
        </th>
        <th>
            SkillLevel
        </th>
        <th>
            Date
        </th>
        <th>
            Text
        </th>
        <th>
            Example
        </th>
        <th>
            Citation
        </th>
        <th>
            Link
        </th>
        <th>
            Rating
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SkillLevel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Example)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Citation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Link)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TipId }) |
            @Html.ActionLink("Details", "Details", new { id=item.TipId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TipId })
        </td>
    </tr>
}

</table>

TipOfTheDay.WebUI/Views/Home/Index.cshtml
@model TipOfTheDay.Domain.Entities.Tip
@using TipOfTheDay.Domain.Entities

@{
    ViewBag.Title = "Index";
}

<div style="width:500px">

    <h1>Programming Tip Of the Day</h1>
        
    @if(Session["User"] == null)
    {
        <p>@Html.ActionLink("Log in", "LogIn", "Member")</p>
    }
    else
    {
       <p>User: @(((Member)Session["User"]).Name)</p>
       <p>Add a tip: @Html.ActionLink("Add a tip", "AddTip", "Admin")</p>
    }

    <h3>@Model.Title</h3>
    Skill Level: @Model.SkillLevel/5 <br /><br />
    @Model.Text<br /><br />
    <code>@Model.Example</code><br /><br />
    Rating: @Model.Rating/5
    <br /><br />
    <cite>@Model.Citation<br /></cite>
    <a href="@Model.Link">@Model.Link</a><br />
    <br />
    <u>Languages:</u> <br />
    @foreach (TipOfTheDay.Domain.Entities.Language lang in @Model.Languages)
    {
        @lang.Name <br />
    }
    <br />
    <U>Tags:</U> <br />
    @foreach (TipOfTheDay.Domain.Entities.Tag tag in @Model.Tags)
    {
        @tag.Word <br />
    }
    <br />
    <U>Comments:</U> <br />
    @foreach (TipOfTheDay.Domain.Entities.Comment com in @Model.Comments)
    {
        @com.Text <br />
        @com.Author.Name <br />
        @com.Date.ToString() <br /> 
    }

    <br />
    @Html.ActionLink("See all tips", "TipList")
</div>

TipOfTheDay.WebUI/Views/Member/LogIn.cshtml
@{
    ViewBag.Title = "Log-in";
}

<h2>Log in</h2>
@using(Html.BeginForm())
{
    @:E-mail address: @Html.TextBox("Email")<br />
    <input type="submit" value="Log in" />
}
<h2>Or Register</h2>
@using(Html.BeginForm())
{
    <p>If you are not already registerd, enter your information here:</p>
    @:Name: @Html.TextBox("Name")<br />
    @:E-mail address: @Html.TextBox("Email")<br />
    <input type="submit" value="Register" />
}

TipOfTheDay.WebUI/Views/Search/FindTipByAuthor.cshtml
@model IEnumerable<TipOfTheDay.Domain.Entities.Member>

@{
    ViewBag.Title = "Search by Author";
}


<h2>Search for a Tip by Author</h2>
@using(Html.BeginForm())
{
    @Html.DropDownList("MemberId", new SelectList(Model, "MemberId", "Name"))

    <input type="submit" value="Search" />
}

TipOfTheDay.WebUI/Views/Search/TipList.cshtml
@model IEnumerable<TipOfTheDay.Domain.Entities.Tip>

@{
    ViewBag.Title = "TipList";
}

<h2>TipList</h2>
@foreach(var tip in Model)
{
  <h3>@tip.Title</h3>
    @:Skill Level: @tip.SkillLevel/5 <br /><br />
    @tip.Text<br /><br />
    <code>@tip.Example</code><br /><br />
    @:Rating: tip.Rating/5
    <br /><br />
    <cite>@tip.Citation<br /></cite>
    <a href="@tip.Link">@tip.Link</a><br />
    <br />
    <u>Languages:</u> <br />
    if(tip.Languages != null)
    {
        foreach (TipOfTheDay.Domain.Entities.Language lang in tip.Languages)
        {
            @lang.Name <br />
        }
    }
    <br />
    <U>Tags:</U> <br />
    if(tip.Tags != null)
    {
        foreach (TipOfTheDay.Domain.Entities.Tag tag in tip.Tags)
        {
            @tag.Word <br />
        }
    }
    <br />
    <U>Comments:</U> <br />
    if(tip.Comments != null)
    {
        foreach (TipOfTheDay.Domain.Entities.Comment com in tip.Comments)
        {
            @com.Text <br />
            @com.Author.Name <br />
            @com.Date.ToString() <br /> 
        }
    }
}

TipOfTheDay.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin.css" rel="stylesheet" type="text/css" />
    <title></title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>